### ISSUE TITLE
Suggestion: pip-installable Pyton package

### ISSUE THREAD

**Issue by sschaetz** [dpretet/svut#23]
Hi, 

I'm a grateful user of svut (it is excellent work 👍) and am wondering if there is any desire to make this package pip installable and turn it into a standard Python package. If you are interested I'd be happy to take that on. Indeed, I took a (very opinionated) stab at it here: https://github.com/dpretet/svut/compare/master...sschaetz:svut:python-package where I am doing the following:

- create a `setup.py` and `pyproject.toml` file which allows for this package to be pip-installable (and I think publishable to [pypi](https://pypi.org/) but I have never done that)
- move all sources into a sub-directory `svut` (this is somewhat of a convention for python packages)
- rename the 2 command line tools to more of a Python convention `snake_case` format
- expose the two command line tools via `setup.py` CLI tools -- this way once you install the python package you have the tools automatically in your path and don't need to mess with `$PATH`

The caveat is that I think I probably broke some of the shell scripts but I'm happy to fix them.

Cheers,
Seb

**Comment by dpretet** [comment]
Hi Seb,

Thanks for your interest and the proposal. That's something I consider since months but didn't take time to do that. 

The only worrying point is about renaming the executables, could you keep the name of the symlinks pointing them to avoid breaking existing flows? That would require a significant amount of changes among people using SVUT nowadays. 

Except that, please go ahead, it will be a pleasure to accept your pull request ☺️

I think it's possible but never did it, publishing a newer version thru GitHub actions would be very great. 

Best,
Damien

**Comment by sschaetz** [comment]
Awesome -- I proposed a set of changes here: https://github.com/dpretet/svut/pull/24

**Comment by dpretet** [comment]
Hi Sebastian,

I followed the instruction in the link you [provided](https://realpython.com/pypi-publish-python-package/#publish-your-package-to-pypi) and everything is ready. Can you give a try please to be sure it's working?

https://pypi.org/project/svut/

Damien

**Comment by sschaetz** [comment]
Congratulations @dpretet -- it works like a charm!

**Comment by dpretet** [comment]
Don't hesitate to request or propose new features. BTW I'm curious how and for what for you use SVUT ☺️

Thanks again Sebastian!
